spring.application.name=movemateback

# Configuración del servidor:
server.port=8080

# Controlador REST:
spring.data.rest.base-path=/api
# Cambia la ruta base de los controladores REST a /api.

# Ajustes de H2:
spring.h2.console.enabled=true
# Activa la consola web de H2, para ver y modificar la base de datos desde el navegador.
spring.h2.console.path=/h2-console
# Define la ruta de la consola web de H2.
# Se accede a través de http://localhost:8080/h2-console
spring.datasource.driver-class-name=org.h2.Driver
# Configura el driver de la base de datos H2.
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Configura el dialecto de H2 para Hibernate.

# Configuración de Hibernate para generar las tablas automáticamente:
spring.jpa.hibernate.ddl-auto=update

# Logs de SQL para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.media-types.json=application/json;charset=UTF-8
spring.mvc.contentnegotiation.favor-parameter=true

# Configuración de la base de datos:
spring.datasource.url=jdbc:h2:file:./data/movemateback
# Configura la URL de la base de datos H2 en memoria.
# La base de datos se crea en memoria y se pierde al cerrar la aplicación.
# En el caso de usar una base de datos no persistente, cambiar a spring.datasource.url=jdbc:h2:mem:movemate


# Usuario y contraseña de la base de datos:
spring.datasource.username=alvaro
spring.datasource.password=alvaro123