spring.application.name=movematefront
server.port = 8083
spring.devtools.livereload.port= 45729
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


clientemanager.server=http://localhost:8080